### ISSUE TITLE
Only display the "welcome" block for logged in users

### ISSUE THREAD

**Issue by pnu-s** [pytition/Pytition#241]
Hello again :)

**Is your feature request related to a problem? Please describe.**
Depending on the context, I find that the block with "Welcome to Pytition - Make things change! - Create a petition" is confusing for new comers who just want to sign petitions and are not logged in

**Describe the solution you'd like**
I would only display this block for logged in users. It is possible of course to add an option to the Django settings to keep the current behaviour for those who want.

**Additional context**
Once again, happy to take care of this change if you want it to be done :)

Cheers!

**Comment by fallen** [comment]
I'm not sure actually, because in what you propose a "new user" would have to first have the idea to click on "connect" then "register" to even have the possibility to see a "create a petition" button.
With the current situation, there is the button, new user can directly click on it, then it will as for an account, they can create one and then they get redirected upon login to their dashboard with nice and clear "new petition" button.

But, I am being careful here, that would not be the first time that, as the writer of the code, I don't see something that's terribly broken because "I know how it works".
So please don't hesitate to prove me wrong, maybe I misunderstood something!
Usually that's the case with UI/UX :)

**Comment by simpnu** [comment]
That's an interesting point.

Actually I think it depends on who your "main target users" are. At first I thought that they are the people who are going on the Pytition instance in order to **sign a petition**. In this case - and if I use the example of https://nonauxjo.org/ - I find it disturbing to see the whole "Create a petition" block.

This being said, I'm not really familiar with the whole registration process on Pytition instances (e.g. can everyone just create an account and a petition?). It may not be the same depending on the instance, that's why I was suggesting to let it as an option in order to let administrators chose.

Note that UI/UX is not my speciality neither. By the way, for [εxodus](reports.exodus-privacy.eu.org/) we used the help of someone who is a specialist and it greatly helped ;)

**Comment by fallen** [comment]
Maybe we can at least remove the "Create a petition" button on home page if `settings.ALLOW_REGISTER == False`?

**Comment by pnu-s** [comment]
@fallen Sure, I can take a look at that!
