### ISSUE TITLE
Allow to chose which social network sharing button to show or not

### ISSUE THREAD

**Issue by fallen** [pytition/Pytition#311]
For now it's either all buttons or none.
Allow to chose which are wanted per-petition.

**Comment by rsk2** [comment]
Hi @fallen, how are you? 

Can I work on this issue?

**Comment by rsk2** [comment]
@fallen in order to implement this, we will need 7 `boolean` fields in the `petition` model (one for the email sharing button and remaining 6 for the social network sharing buttons). Each field will indicate whether a particular sharing button needs to be shown or not. Please let me know if you need any changes in this approach.

**Comment by rsk2** [comment]
@fallen should I add make these field changes for the `PetitionTemplate` model as well?
